### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by LuckyYam** [GizmolabAI/DiscordBot-GL#1]
Please make a WhatsApp bot using the same packages.

**Comment by gizmo-dev** [comment]
Heyo! I cant use the same packages as they are specifically tailored for Discord.js! Still I can Try to do something similar on whatsapp bots too! Hit Me Up on My discord so we can discuss about this!✌ GIZMO#5611

**Comment by LuckyYam** [comment]
> Heyo! I cant use the same packages as they are specifically tailored for Discord.js! Still I can Try to do something similar on whatsapp bots too! Hit Me Up on My discord so we can discuss about this!✌ GIZMO#5611

Thanks. I'll contact you within 24 hours.
